services:
  mongodb:
    image: mongo:4.4.26
    container_name: ocean-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ocean-backend
    restart: always
    ports:
      - "8080:8001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    volumes:
    # Location on server : Location in container (Leave this as /data/)
      - /mnt/ocims-somisana/public-facing/:/data/
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    name: ocean_model_visualiser_mongodb_data
